global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'wordpress'
    static_configs:
      - targets: ['wordpress:8000']

  - job_name: 'mysql'
    static_configs:
      - targets: ['db:3306']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']